# -*- coding: utf-8 -*-
"""Number Plate Recognition using Theos OCR

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1am0j610wtsUw0I3k6FT-MX7h4TJCXWeY
"""

!pip install utils

import utils
import cv2
import time
import os
import requests

URL = 'https://inf-76370045-724e-413b-960f-6e28fa989274-no4xvrhsfq-uc.a.run.app/detect'  # Theos API URL
OCR_MODEL = 'large'
OCR_CLASS = 'license-plate'
FOLDER_PATH = 'license-plates'
seconds_to_wait = 2

img = cv2.imread('/content/Cars1.png')

_, img_encoded = cv2.imencode('.jpg', img)
image_bytes = img_encoded.tobytes()

response = requests.post(URL, data={'ocr_model': OCR_MODEL, 'ocr_classes': OCR_CLASS}, files={'image': image_bytes})
if response.status_code == 200:
    data = response.json()

    if len(data) > 0:
        license_plates = []

        for detection in data:
            if detection['class'] == OCR_CLASS and detection['text']:
                license_plates.append(detection['text'].upper())

        if len(license_plates) > 0:
            print('License plates:', ', '.join(license_plates))

